language: python
python:
- 3.9
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  twine_version: 3.4.1
  user: tkasu
  password:
    secure: CpPTVKevIVcEgV/1Ecpu6l4P6208Iou6Z/fR0goIJHCqdQxtfgxbjKN3haJMUDoAyKK8iIy59LK429kuE8TudkHQkbbGGWtZpyeH6d6rS0S+r7NiKEFEp7x2gz17Uw7eaEu/u8YL/PkxU51UkK/tMUV+3RVnxoUTGwQEXvvKZotSk0PF/yaS4hY3BsdmIGswa2brVrliskrcBnX0aIYP0oULQyxUfPVIBMTuaGxP/+X1n8tsquL6DoOQOQk2r80NZLBOpH1GwvIVDM2tNo8MdTGVH2b12x0FU+6K2SX7UX7Y/sS9ZAr2rZWVeSzgjlrlZNo25OSX6TZ2AQ2Plb5B2B5VoCQMHnocIS4sBBNm7SR7euwDkH6jSA5yl9UI3tKTd7HRyOwns7WeARjbzeJetohSInzXwEw9XF0Z1UAkATdBcxjw1j34BOYyxsJ0twiw+iVWJS7mG+DeBYyWgKECG6mQqks5eyldQbqJrNk64+oJbYUmesHCK7NUysRfgv21JyOQD686NBwdI4ymjFHbbc6G9Vw+88XzqJUbsHpKuUoUG9ZrMLFSlXKkBgqw+rrVWNw7UcRWspFifSsf1d3dsCIGI2CCBaeBwPx/wmmwZ95k2Mr+V+XqG+b0k15OgEhJjQJSIlrzoUUOl8WLhMBZ0wRXHbCpCq8v0pQabTJUtSw=
  on:
    tags: true
    repo: tkasu/badger_batcher
    python: 3.9
