language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tkasu
  password:
    secure: VDy6/6ipfxQZc9zDyPTlhRoBT9a6co19LPtbRstAuF86ZJeOvvUNsZifJklc/16FgJ8ALf0XOS9e056X+OMfABsTfi7IT/AJKYZtwAQBSsnQaBDVzpze5jeJAqUjF/qqODa873Qqe3SPzW/tjDtFffS1OxMc/FPqr83hSpbIn3WJhozC25CLnGn2cGqChv3SPgerhTb30AqFjd8dHMEQzauq9zUra2Lq/l2P66BdktvJMmYb4c9leny9VbtMRT6hBVij9vEH7NoJLrMU8EKTzOuleWqAydANIwmeQcaEVnXIEG3K3NVkcpVyGrEboV/HpQNyTBCqFhXDFSx+b+SLjQq5tnHl7TY2/NOl2zand/YD5peFJeMEXg5ZsgobZZdYsj/O/tkkZS6njbxf0+/sVTE84SoYUEOJn202GdRNnsoarx1sz8834zY62IGIosm1mDX+Rqg1AVJR2t/dzL9ZtBGAvvsO126Qz+avhpr9hTxzEFlmTvOVAQYZLHRi2qv8/IhYeDAQ2Aj2McIq/b6WpklC7MspiAzUR6g4IRc5GtmhLH8t9P9uGTpsbUCbllvKR12lISlE+OBE+PdI1qHZdK9vm+Wo7hz/E2vNfCETaKQoBgryDz7N/BW+kRsJHQ5N0wZA247OHuetsNO/mIjKEgRYXX1wB7V+vvOhFe/a2SQ=
  on:
    tags: true
    repo: tkasu/badger_batcher
    python: 3.9
